name:                goodTimerHaskell
version:             0.1.0.0
github:              "githubuser/goodTimerHaskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/goodTimerHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-types
- gogol-core
- gogol-firestore
- aeson
- text
- split
- bytestring
- hspec == 2.10.10
- QuickCheck == 2.14.3
- containers
- cassava
- MissingH

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  goodTimerHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - goodTimerHaskell

tests:
  goodTimerHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    defaults: hspec/hspec@main
    dependencies:
    - goodTimerHaskell
    - hspec == 2.10.10
    - QuickCheck == 2.14.3
